# Generated by Django 6.0.3 on 2026-03-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
